import type { Metadata } from "next";

import { pageMetadata } from "@/lib/seo";
import { GITHUB_EDITOR_REPO, GITHUB_EDITOR_URL, GITHUB_ORG } from "@/lib/site";
import { TEXT_LINK } from "@/lib/ui";

export const metadata: Metadata = pageMetadata({
  title: "Privacy Policy",
  description:
    "How the Aphelion website, accounts, payments, licensing system and desktop application handle your data.",
  path: "/privacy",
});

const ISSUES_URL = `${GITHUB_EDITOR_URL}/issues`;
const VERCEL_PRIVACY_URL = "https://vercel.com/legal/privacy-policy";
const GITHUB_PRIVACY_URL =
  "https://docs.github.com/site-policy/privacy-policies/github-general-privacy-statement";

export default function PrivacyPage(): React.ReactElement {
  return (
    <div className="mx-auto max-w-3xl px-4 py-12 lg:py-14">
      <h1 className="aph-page-title">Privacy</h1>
      <p className="mt-3 text-muted">
        This page covers the Aphelion website, workspace accounts, license purchases and the
        Aphelion Editor desktop application. The website now uses accounts, payment processing and
        limited analytics; the desktop editor remains local and does not send telemetry.
      </p>

      <div className="aph-dock mt-8">
        <div className="aph-dock__title">Summary</div>
        <div className="aph-dock__body">
          <ul className="space-y-2 text-sm text-muted">
            <li>Accounts use Firebase Authentication for email/password and Google sign-in.</li>
            <li>PayPal processes payment details; Aphelion does not receive or store card numbers.</li>
            <li>License records contain account, purchase and product-redemption information.</li>
            <li>Firebase Analytics may collect website usage and device information for measurement.</li>
            <li>The website reads public GitHub data on the server, not from your browser.</li>
            <li>The editor runs locally, ships no telemetry and keeps your files on your machine.</li>
          </ul>
        </div>
      </div>

      <section className="mt-10">
        <h2 className="aph-section-title">Accounts and authentication</h2>
        <ul className="mt-4 space-y-3 text-sm text-muted">
          <li>
            When you create an account or sign in, Firebase Authentication processes your email
            address and authentication credentials. Google sign-in is handled by Google according to
            Google&apos;s own privacy terms.
          </li>
          <li>
            The site uses your Firebase account identifier to associate purchases and license records
            with your workspace. You can sign out from Account settings.
          </li>
          <li>
            Authentication session data is stored by Firebase in your browser so the site can keep you
            signed in. You can clear it by signing out or clearing site data.
          </li>
        </ul>
      </section>

      <section className="mt-10">
        <h2 className="aph-section-title">Payments and licenses</h2>
        <ul className="mt-4 space-y-3 text-sm text-muted">
          <li>
            Checkout takes place through PayPal. PayPal handles payment credentials and returns
            payment status to the site; Aphelion does not store your full payment details.
          </li>
          <li>
            To fulfill a purchase, the site stores a PayPal order or capture reference, your Firebase
            account identifier, the purchase amount and currency, and the date of fulfillment.
          </li>
          <li>
            License keys are generated by the server. The raw key is shown once after a verified
            payment; the licensing service stores a protected representation and safe metadata rather
            than displaying the full key in Account settings.
          </li>
          <li>
            When a product redeems a key, the service records the product identifier, account binding,
            product version when supplied, and redemption time. Each license can be redeemed once per
            product.
          </li>
        </ul>
      </section>

      <section className="mt-10">
        <h2 className="aph-section-title">Analytics and hosting</h2>
        <ul className="mt-4 space-y-3 text-sm text-muted">
          <li>
            Firebase Analytics is loaded in the browser when supported. It may process page views,
            browser or device information and approximate usage events. Analytics is not used by the
            desktop editor.
          </li>
          <li>
            The site is hosted on Vercel. Vercel keeps standard request logs for every deployment,
            which can include an IP address, a user agent and the requested path. Those logs are used
            for operations, capacity and abuse prevention. Vercel&apos;s handling of them is described in
            the{" "}
            <a className={TEXT_LINK} href={VERCEL_PRIVACY_URL} target="_blank" rel="noreferrer">
              Vercel privacy policy
            </a>
            .
          </li>
        </ul>
      </section>

      <section className="mt-10">
        <h2 className="aph-section-title">This website</h2>
        <ul className="mt-4 space-y-3 text-sm text-muted">
          <li>
            The site does not use advertising or session-recording code. Firebase Authentication may
            store session state in browser storage, and Firebase Analytics may use its own measurement
            storage where supported.
          </li>
          <li>
            Release lists and documentation are read from the public GitHub API when a page is
            rendered. Those requests are made by the server, so your IP address and browser are not
            sent to GitHub by visiting a page.
          </li>
          <li>
            Builds and documentation links point at github.com. Once you follow one of those links,
            GitHub&apos;s own practices apply. See the{" "}
            <a className={TEXT_LINK} href={GITHUB_PRIVACY_URL} target="_blank" rel="noreferrer">
              GitHub privacy statement
            </a>
            .
          </li>
        </ul>
      </section>

      <section className="mt-10">
        <h2 className="aph-section-title">The desktop application</h2>
        <ul className="mt-4 space-y-3 text-sm text-muted">
          <li>
            The editor runs entirely on your computer. Projects, media references, preferences,
            logs and plugins are written to the locations you choose and are never uploaded.
          </li>
          <li>
            There is no telemetry, crash reporting, usage counting or update check. The editor does
            not contact a server on its own.
          </li>
          <li>
            Media decoding, the video encoder and the plugin runtime are bundled with the
            application. Nothing needs to be downloaded at run time.
          </li>
          <li>
            If you install a plugin written by someone else, that plugin runs in the same process
            and can do whatever its author wrote. Install plugins from sources you trust.
          </li>
        </ul>
      </section>

      <section className="mt-10">
        <h2 className="aph-section-title">Changes and contact</h2>
        <p className="mt-4 text-sm text-muted">
          If any of the above changes, this page will be updated before the change ships. Questions
          about this policy can go in the{" "}
          <a className={TEXT_LINK} href={ISSUES_URL} target="_blank" rel="noreferrer">
            issue tracker
          </a>{" "}
          for {GITHUB_ORG}/{GITHUB_EDITOR_REPO}.
        </p>
        <p className="mt-3 font-mono text-[11px] text-muted">Last updated 21 September 2026.</p>
      </section>
    </div>
  );
}
